In [1]:
from Scikit_Extensions_For_Stocks.time_series_scaler import Linear1DLogGainScaler, Linear2DLogGainScaler
import numpy as np
import pandas as pd

In [2]:
DF = pd.DataFrame(data=[[10.1,2.1,3.1,4.1,5.1],[6,7,8,9,10]])
DF = DF.T
DF.columns = ['A','B']
DF

A     B
0  10.1   6.0
1   2.1   7.0
2   3.1   8.0
3   4.1   9.0
4   5.1  10.0

In [3]:
sc = Linear1DLogGainScaler()
K = sc.fit_transform(DF['A'])
K

0    0.000000
1   -0.682102
2    0.169142
3    0.121422
4    0.094786
Name: A, dtype: float64

In [4]:
sc.inverse_transform(K)

array([10.1,  2.1,  3.1,  4.1,  5.1])

In [5]:
np.isclose(sc.inverse_transform(K),DF['A'])

array([ True,  True,  True,  True,  True])

In [6]:
DF

A     B
0  10.1   6.0
1   2.1   7.0
2   3.1   8.0
3   4.1   9.0
4   5.1  10.0

In [7]:
sc = Linear1DLogGainScaler()
DF2 = pd.DataFrame()
DF2['A'] = sc.fit_transform(DF['A'])
DF2['B'] = DF2['A'] - 0.001
DF2

A         B
0  0.000000 -0.001000
1 -0.682102 -0.683102
2  0.169142  0.168142
3  0.121422  0.120422
4  0.094786  0.093786

In [8]:
DF2['A_actual'] = sc.inverse_transform(DF2['A'])

In [9]:
DF2

A         B  A_actual
0  0.000000 -0.001000      10.1
1 -0.682102 -0.683102       2.1
2  0.169142  0.168142       3.1
3  0.121422  0.120422       4.1
4  0.094786  0.093786       5.1

In [10]:
DF2['B_actual'] = DF2.apply(lambda x: (10**(x['B']-x['A']))*x['A_actual'],axis=1)

In [11]:
DF2

A         B  A_actual   B_actual
0  0.000000 -0.001000      10.1  10.076771
1 -0.682102 -0.683102       2.1   2.095170
2  0.169142  0.168142       3.1   3.092870
3  0.121422  0.120422       4.1   4.090570
4  0.094786  0.093786       5.1   5.088270

In [12]:
from Scikit_Extensions_For_Stocks.time_series_scaler import LogScale1D

In [22]:
sc = LogScale1D()
kkkk = sc.transform(DF2['A_actual'])

In [23]:
np.isclose(sc.inverse_transform(kkkk),DF2['A_actual'])

array([False, False, False, False, False])

In [25]:
pd.DataFrame(sc.inverse_transform(kkkk))

0
0  1.044064
1  0.000012
2  0.000820
3  0.007466
4  0.031455